[[ -s ~/.bashrc ]] && source ~/.bashrc

PATH=$PATH:~/bin

#alias emacs="/usr/local/Cellar/emacs/24.4/Emacs.app/Contents/MacOS/Emacs"
#alias emacsclient="/usr/local/Cellar/emacs/24.4/bin/emacsclient"

#[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
