# Ensure keymap is bound to emacs mode
bindkey -e

# Don't exit the shell when typing Ctrl-d on an empty line
setopt ignore_eof

alias exut='exit'
alias exot='exit'

path+=("$HOME/bin")
path+=("$HOME/bin/sbt/bin")
path+=("$HOME/bin/apache-maven-3.6.3/bin")
path+=("$HOME/.cargo/bin")
path+=("$HOME/anaconda3/bin")
path+=("$HOME/bin/spark/bin")

# export to sub-processes (make it inherited by child processes)
export PATH


# OS X ships with BSD ls rather than GNU ls
# Add color to ls output
if [ "$(uname)" = "Darwin" ]; then
    export CLICOLOR=1
    export LSCOLORS=GxFxCxDxBxegedabagaced
fi

export GIT_EDITOR=emacs
export GIT_AUTHOR_NAME="Will Fleming"
export GIT_AUTHOR_EMAIL=wfleming77@gmail.com
export GIT_COMMITTER_NAME="$GIT_AUTHOR_NAME"
export GIT_COMMITTER_EMAIL="$GIT_AUTHOR_EMAIL"


# List tmux sessions on login. If none, don't show the error.
# Only run in an interactive shell since it writes to stdout, which breaks scp
case "$-" in
    *i*) tmux list-sessions 2> /dev/null
esac


#zstyle ':completion:*:*:git:*' script ~/.git-completion.zsh
#[[ -e ~/.git-completion.zsh ]] && source ~/.git-completion.zsh

autoload -Uz compinit && compinit

[[ -e ~/.git-prompt.sh ]] && source ~/.git-prompt.sh
setopt PROMPT_SUBST ; PS1='[%n@%m %c$(__git_ps1 " (%s)")]\$ '

export PATH="/usr/local/opt/openjdk/bin:$PATH"

# On OS X with java 8 and 11 installed, use 8
# alias j11="export JAVA_HOME=`/usr/libexec/java_home -v 11`"
# alias j8="export JAVA_HOME=`/usr/libexec/java_home -v 1.8`"
# j8

# https://github.com/asdf-vm/asdf
. $(brew --prefix asdf)/asdf.sh

# If ruby installed via homebrew add it to the path
# export PATH="/usr/local/opt/ruby/bin:$PATH"

# If a file named .work exists, source it
[ -f .work ] && source .work

# Include docs when building Erlang via asdf
# This will make the Erlang docs available in Elixir's iex help functionality
# For example `h :unicode.bom_to_encoding`
export KERL_BUILD_DOCS="yes"

# Enable shell history in iex and erl
export ERL_AFLAGS="-kernel shell_history enabled -kernel shell_history_file_bytes 1024000"
