{:user {:plugins [[jonase/eastwood "0.2.1"]
                  [lein-cljsbuild "1.0.5"]
                  [lein-try "0.4.3"]
                  [lein-simpleton "1.3.0"]
                  [com.jakemccrary/lein-test-refresh "0.9.0"]
                  [lein-kibit "0.1.2"]
                  [lein-pprint "1.1.1"]
                  ;[lein-ancient "0.6.7"]
                  [cider/cider-nrepl "0.9.0-SNAPSHOT"]
                  [codox "0.8.12"]] }}
